// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmeyxovxmuwkehfaplaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZXl4b3Z4bXV3a2VoZmFwbGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDg0NjMsImV4cCI6MjA2MzkyNDQ2M30.mhP9uvUdADBFIBB33V5n608nSI1MGHjmdm4ziTAwzMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);